# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - gridExtra
  - tibble
r_github_packages:
  - rforge/bayesr/pkg/bamlss
  - Stan125/gamlss.dist
notifications:
  email:
    - stadlmann@uni-goettingen.de
