# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - tibble
  - glogis
r_github_packages:
  - Stan125/gamlss.dist
  - thomasp85/patchwork
notifications:
  email:
    - stadlmann@uni-goettingen.de
install:
  - R -e "install.packages('bamlss', repos = 'http://R-Forge.R-project.org')"
